# frozen_string_literal: true

source "https://rubygems.org"

ruby '2.4.3'

git_source(:github) {|repo_name| "https://github.com/#{repo_name}" }

# gem "rails"

# Added at 2017-12-24 10:49:38 +0000 by nicholaw:
gem "numo-narray", "~> 0.9.0"
